### ISSUE TITLE
Projects missing .csv and .ipynb files

### ISSUE THREAD

**Issue by timmot** [michiganrobotics/rob101#1]
Thanks so much for making this course publicly available!

Are you able to include the Illumidesk attachments for each project?

Tentative list of missing files:
- project_1.ipynb
- data/question.csv
- data/cassei_data/*
- p1_basis_functions.pynb
- p2_alaska.ipynb
- project 3?

**Comment by michiganrobotics** [comment]
Hi @timmot,

We did not post these on purpose.

If you are a teacher, however, we are happy to share them: please send Dan a note at dnewms@umich.edu with your school information.

Thanks!

**Comment by timmot** [comment]
Thanks for the clarification, closing out this issue.

**Comment by AgnelFernando** [comment]
Hi @michiganrobotics,

I am also in need of these documents. Could you please advise me on who I should contact for this matter? I have already sent an email to Dan, but unfortunately, I have not received any response.

**Comment by michiganrobotics** [comment]
Hello, you can find the latest project files in the latest course folders: https://github.com/michiganrobotics/rob101/tree/main/Fall%202022%20%26%20Winter%202023/Projects/Project01
